{% set version = "2.3.1" %}

package:
  name: libidn2
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/libidn/libidn2-{{ version }}.tar.gz
  sha256: 8af684943836b8b53965d5f5b6714ef13c26c91eaa36ce7d242e3d21f5d40f2d

build:
  skip: true  # [win]
  number: 0
  run_exports:
    # _Amazing_ backwards compatibility so pin to major number:
    #    https://abi-laboratory.pro/tracker/timeline/libidn2/
    - {{ pin_subpackage('libidn2', min_pin='x', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - gettext
    - libunistring

test:
  commands:
    - test -f "${PREFIX}/include/idn2.h"
    - test -f "${PREFIX}/lib/libidn2${SHLIB_EXT}"

about:
  home: https://www.gnu.org/software/libidn/#libidn2
  license: LGPLv2
  license_file: COPYING
  summary: Library for internationalized domain names (IDNA2008) support

extra:
  recipe-maintainers:
    - hmaarrfk
    # This recipe I got from
    # - chenghlee
